// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiwU3rBD0QTzRy3GDg8HU6iw_qfFnshd4',
    appId: '1:601981977387:web:9b6436ac48ad37fe8cbb6e',
    messagingSenderId: '601981977387',
    projectId: 'e-commerce-c5b8c',
    authDomain: 'e-commerce-c5b8c.firebaseapp.com',
    storageBucket: 'e-commerce-c5b8c.appspot.com',
    measurementId: 'G-GP0BFZP6YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsC0-oXWAaTnvbFcmIS5XyPfc0OmiQJuU',
    appId: '1:601981977387:android:36530076267168b68cbb6e',
    messagingSenderId: '601981977387',
    projectId: 'e-commerce-c5b8c',
    storageBucket: 'e-commerce-c5b8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgWHAtV8Q61Zs_b-TZyReQi8kctRnlvVI',
    appId: '1:601981977387:ios:293e5cf35fe1fdb08cbb6e',
    messagingSenderId: '601981977387',
    projectId: 'e-commerce-c5b8c',
    storageBucket: 'e-commerce-c5b8c.appspot.com',
    iosClientId: '601981977387-a8iifvpbp80041pa7hc1mkjo56jbuatb.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );
}
